version: '3'
services:
  task1:
    build: ./main
    image: task1
    container_name: task1
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - ./main:/go/src/app
    networks:
      app_net:
        ipv4_address: 172.16.238.2

  task1_test:
    build: ./sub
    image: task1_test
    container_name: task1_test
    tty: true
    stdin_open: true
    ports:
      - "6000:6000"
    networks:
      app_net:
        ipv4_address: 172.16.238.3

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.16.238.0/24
         gateway: 172.16.238.1